# Generated by Django 5.0 on 2024-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
